initial_orientation = ...
initial_time = ...
rotation_rate = ...
original_frame = "J2000"
target_frame = "Earth_Fixed_Simplified"

body_settings.get( "Earth" ).rotation_model_settings = environment_setup.rotation_model.simple( 
	original_frame, target_frame,  initial_orientation, initial_time, rotation_rate)
