# Add empty body settings for body Oumuamua, and add to existing list of settings 
body_settings.add_empty_settings( "Oumuamua" )

# Manually create and assign environment model settings to new body settings
body_settings.get( "Oumuamua" ).ephemeris_settings = ...	
body_settings.get( "Oumuamua" ).gravity_field_settings = ...
body_settings.get( "Oumuamua" ).rotation_model_settings = ...
