axis_a = ...
axis_b = ...
axis_c = ...
density = ...
maximum_degree = ...
maximum_order = ...
associated_reference_frame = ...

body_settings.get( "Earth" ).gravity_field_settings = environment_setup.gravity_field.spherical_harmonic_triaxial_body( 
	gravitational_parameter, axis_a, axis_b, axis_c, density, maximum_degree, maximum_order)
