name: tudat-docs
channels:
  - conda-forge
dependencies:
  - python=3.14
  - sphinx=9.1
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton
  - nbsphinx
  - ipython
  - ipykernel
  - pandoc
  - sphinx-codeautolink